### ISSUE TITLE
Decimal Ratio on iOS

### ISSUE THREAD

**Issue by Twister915** [antlionguard/calculate-coffee#5]
Hi,

I like a 17.5:1 ratio, and was able to enter this on my computer on your V60 Calculator For Tetsu Kasuya Technique. However on my iPhone the digit entry keyboard comes up and does not have a decimal point available. Could you consider changing the input type to permit me to enter a decimal value in the ratio field?

Thanks!

**Comment by antlionguard** [comment]
> Hi,
> 
> I like a 17.5:1 ratio, and was able to enter this on my computer on your V60 Calculator For Tetsu Kasuya Technique. However on my iPhone the digit entry keyboard comes up and does not have a decimal point available. Could you consider changing the input type to permit me to enter a decimal value in the ratio field?
> 
> Thanks!

i will be checking today. thanks for your feedback!

**Comment by antlionguard** [comment]
I released new version for this issue. Do not forget to clean your cache. Enjoy your brews!

**Comment by Twister915** [comment]
@antlionguard hi, thank you, I see the decimal point now! However when I try to type a number into the coffee weight field, it instantly closes and accepts 0 as the input. I think this release included a new bug? I can record a video if you cannot reproduce.

**Comment by Twister915** [comment]
@antlionguard I can verify that there are similar issues when clicking & typing in that field ("Coffee Weight") on Desktop as well.

**Comment by antlionguard** [comment]
> @antlionguard I can verify that there are similar issues when clicking & typing in that field ("Coffee Weight") on Desktop as well.

Yep my bad. I fixed that. Live in 5min.

**Comment by Twister915** [comment]
Thank you!! We are sipping on some delicious cups this morning thanks to your calculator
